spring:
  application:
    name: user-manage
  profiles:
    active: ${ENV_NAME:dev}
  datasource:
#    url: jdbc:mysql://192.168.30.34:3306/user_manage?useSSL=false&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/hezu?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
#    password: 123456
    password: aa123123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000
  servlet:
      context-path: /


swagger:
  base-package: com.tangquan
  base-path: /**
  exclude-path: /error
  globalOperationParameters[0]:
      name: Authorization
      modelRef: string
      parameterType: header
      description: jwt

user_manage_log: log

tq:
  framework:
    jwt:
      secret: www.itangquan.com
      ttl-seconds: 36000
      refresh-window-seconds: 60

cbank:
  local:
    bankCode: C1010332000030 #网点 默认金库

aliyun:
  key: LTAIjLMuN7bqjTX1
  secret: HoyrK56Syz39tUA46ccjpfj5NP51qV
  bucketName: hezu
  endpoint: oss-cn-beijing.aliyuncs.com
  domain: hezu.oss-cn-beijing.aliyuncs.com