-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 11:14:48 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user_manage
-- -----------------------------------------------------
-- 用户管理

-- -----------------------------------------------------
-- Schema user_manage
--
-- 用户管理
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_manage` DEFAULT CHARACTER SET utf8 ;
USE `user_manage` ;

-- -----------------------------------------------------
-- Table `user_manage`.`tq_admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_admin_user` (
  `id` SMALLINT(10) NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(20) NOT NULL COMMENT '登录名',
  `user_name` VARCHAR(20) NOT NULL COMMENT '用户名',
  `password` VARCHAR(100) NOT NULL COMMENT '密码',
  `status` TINYINT(1) NOT NULL COMMENT '状态',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_name_UNIQUE` (`login_name` ASC))
ENGINE = InnoDB
COMMENT = '管理员';


-- -----------------------------------------------------
-- Table `user_manage`.`tq_admin_user_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_admin_user_bank` (
  `uid` SMALLINT(10) NOT NULL,
  `bank_ids` VARCHAR(120) NOT NULL COMMENT '多级银行编码，”｜”分隔',
  `bank_id` VARCHAR(45) NOT NULL COMMENT '银行金融编码',
  PRIMARY KEY (`uid`))
ENGINE = InnoDB
COMMENT = '管理员与银行关联';


-- -----------------------------------------------------
-- Table `user_manage`.`tq_auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL COMMENT '名称',
  `status` TINYINT(1) NOT NULL COMMENT '状态\n1:开启\n0:关闭',
  `group_type` SMALLINT(1) NOT NULL COMMENT '权限组类别\n1.超级管理员组\n2.普通管理员组',
  `rules` VARCHAR(1000) NULL COMMENT '规则id，以“,”号分隔',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
COMMENT = '权限组';


-- -----------------------------------------------------
-- Table `user_manage`.`tq_auth_group_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_auth_group_access` (
  `uid` SMALLINT(10) NOT NULL COMMENT '用户id',
  `group_id` INT NOT NULL COMMENT '权限组id',
  PRIMARY KEY (`uid`))
ENGINE = InnoDB
COMMENT = '用户与权限组关联';


-- -----------------------------------------------------
-- Table `user_manage`.`tq_auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_auth_rule` (
  `id` SMALLINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL COMMENT '规则路径',
  `title` VARCHAR(20) NOT NULL COMMENT '规则名称',
  `status` TINYINT(1) NOT NULL COMMENT '状态',
  `pid` SMALLINT(10) NOT NULL COMMENT '父规则id',
  `icon` VARCHAR(45) NOT NULL COMMENT '图标名称',
  `sort` TINYINT(4) NOT NULL COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '权限规则';


-- -----------------------------------------------------
-- Table `user_manage`.`tq_admin_login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manage`.`tq_admin_login_log` (
  `id` SMALLINT(10) NOT NULL AUTO_INCREMENT,
  `uid` SMALLINT(10) NOT NULL COMMENT '用户id',
  `last_login_time` DATETIME NOT NULL COMMENT '最后登录时间',
  `last_login_ip` VARCHAR(20) NOT NULL COMMENT '最后登录ip',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户登录日志表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
